name: Invitation to the GitHub Community Organization
description: I would like to be part of the awesome community
title: "Please invite me to the GitHub Community Organization"
labels: ["invite me to the organisation"]

body:
  - type: input
    id: name
    attributes:
      label: Full Name
      placeholder: Insert your full name here
    validations:
      required: true

  - type: input
    id: discordname
    attributes:
      label: Discord Username (Optional)
      placeholder: Insert your Discord username here (if applicable)
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Where did you hear about Magic-Academy? What interests you about this community or why do you want to join?
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Join Our Community

        You can also join our Discord community [here](https://discord.gg/G2jgHeQfy4).

        Feel free to explore other cool repositories of the Magic-Academy Community [here](https://github.com/Magic-Academy/).

        ### Instructions

        - Fill out the form above with the requested information.
        - Click "Submit new issue" to send your invitation request.
        - An administrator will review your request and send you an invitation to join the GitHub organization.

        We look forward to welcoming you to the Magic-Academy community!